skills = [
	'Acting',
	'Artisan',
	'Calligraphy',
	'Courtier',
	'Divination',
	'Etiquette',
	'Games',
	'Investigation',
	'Lore: Anatomy',
	'Lore: Architecture',
	'Lore: Bushido',
	'Lore: Elements',
	'Lore: Ghosts',
	'Lore: Heraldry',
	'Lore: History',
	'Lore: Maho',
	'Lore: Nature',
	'Lore: Omens',
	'Lore: Shadowlands',
	'Lore: Shugenja',
	'Lore: Spirit Realms',
	'Lore: Theology',
	'Lore: Underworld',
	'Lore: War',
	'Medicine',
	'Meditation',
	'Perform: Biwa',
	'Perform: Dance',
	'Perform: Drums',
	'Perform: Flute',
	'Perform: Oratory',
	'Perform: Puppeteer',
	'Perform: Samisen',
	'Perform: Song',
	'Perform: Storytelling',
	'Sincerity',
	'Spellcraft',
	'Tea Ceremony',
	'Athletics',
	'Battle',
	'Defense',
	'Horsemanship',
	'Hunting',
	'Iaijutsu',
	'Jiujutsu',
	'Chain Weapons',
	'Heavy Weapons',
	'Kenjutsu',
	'Knives',
	'Kyujutsu',
	'Ninjutsu',
	'Polearms',
	'Spears',
	'Staves',
	'War Fan',
	'Animal Handling',
	'Commerce',
	'Craft: Armorsmithing',
	'Craft: Blacksmithing',
	'Craft: Bowyer',
	'Craft: Brewing',
	'Craft: Carpentry',
	'Craft: Cartography',
	'Craft: Cobbling',
	'Craft: Cooking',
	'Craft: Farming',
	'Craft: Fishing',
	'Craft: Masonry',
	'Craft: Mining',
	'Craft: Poison',
	'Craft: Pottery',
	'Craft: Shipbuilding',
	'Craft: Tailoring',
	'Craft: Weaponsmithing',
	'Craft: Weaving',
	'Engineering',
	'Sailing',
	'Forgery',
	'Intimidation',
	'Sleight of Hand',
	'Stealth',
	'Temptation',
	'Initiative',
	'Honor',
	'Glory',
	'Earth',
	'Status',
	'Rank',
	'Stamina',
	'Willpower',
	'Water',
	'Strength',
	'Perception',
	'Air',
	'Reflexes',
	'Awareness',
	'Fire',
	'Agility',
	'Intelligence',
	'Void'
];